{% set name = "hvplot" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hvplot-{{ version }}.tar.gz
  sha256: feadb395ac01a0be5fc89155452446c2b9c412a99d63eac029083138163d5c1b

build:
  number: 0
  # panel >=0.13.0 and nodejs aren't available on s390x
  skip: True # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pyct >=0.4.4
    - param >=1.7.0
    - pip
    - setuptools >=30.3.0
    - wheel
  run:
    - python
    - packaging
    - bokeh >=1.0.0
    - colorcet >=2
    - holoviews >=1.11.0
    - numpy >=1.15    
    - pandas

test:
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews
  description: |
    A high-level plotting API for pandas, dask, xarray, and networkx built on HoloViews
  dev_url: https://github.com/holoviz/hvplot
  doc_url: https://hvplot.holoviz.org

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt