{% set version = "0.6.0" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: 8fcf2f251bd9d4b0390d9c272c992aa75e11174829e416a22de8fba38acc1ce9

build:
  number: 0
  noarch: python
  # ModuleNotFoundError: No module named 'hvplot.__main__'
  # entry_points:
  #   - hvplot = hvplot.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bokeh >=1.0.0
    - colorcet >=2
    - holoviews >=1.11.0
    - numpy >=1.15
    - pandas

test:
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
    - hvplot --help
  requires:
    - pip

about:
  home: https://pyviz.github.io/hvplot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
