{% set version = "0.7.3" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: 74b269c6e118dd6f7d2a4039e91f16a193638f4119b4358dc6dbd58a2e71e432

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - pyct >=0.4.4
    - param >=1.6.1
  run:
    - python
    - bokeh >=1.0.0
    - colorcet >=2
    - holoviews >=1.11.0
    - numpy >=1.15
    - pandas

test:
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hvplot.holoviz.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews
  dev_url: https://github.com/holoviz/hvplot
  doc_url: https://nbsite.holoviz.org/

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
