{% set version = "0.3.0" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: dfc1dc3da89a77bf0f28db7e11cd3ba29d56c111245940e25cfe13b4ef2a5410

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bokeh >=0.12.15
    - holoviews >=1.10.5
    - pandas

test:
  imports:
    - hvplot
    - hvplot.examples
    - hvplot.examples.assets
    - hvplot.examples.user_guide
    - hvplot.examples.user_guide.images
    - hvplot.tests

about:
  home: https://pyviz.github.io/hvplot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
