{% set name = "hvplot" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hvplot-{{ version }}.tar.gz
  sha256: 9e29bbe65f94937d4eeaeccf33566540df936c8f9aeadfa12ea9f306d5237938

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling >=1.25.0
    - hatch-vcs >=0.4.0
  run:
    - python
    - bokeh >=3.1
    - colorcet >=2
    - holoviews >=1.19.0
    - numpy >=1.21
    - packaging
    - pandas >=1.3
    - panel >=1.0
    - param >=1.12.0,<3.0

test:
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews
  description: |
    A high-level plotting API for pandas, dask, xarray, and networkx built on HoloViews
  dev_url: https://github.com/holoviz/hvplot
  doc_url: https://hvplot.holoviz.org

extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
