{% set version = "0.8.1" %}

package:
  name: hvplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hvplot/hvplot-{{ version }}.tar.gz
  sha256: 53ddfe06743c4d5924fb1e597655bfa14e80feaf57a438bfd28442d36ac7c2b6

build:
  skip: True # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pyct >=0.4.4
    - param >=1.12.0
    - pip
    - setuptools
    - wheel
  run:
    - python
    - packaging
    - bokeh >=2.0.0
    - colorcet >=2
    - holoviews >=1.12.0
    - numpy >=1.15    
    - pandas

test:
  imports:
    - hvplot
    - hvplot.pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hvplot.holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews
  dev_url: https://github.com/holoviz/hvplot
  doc_url: https://hvplot.holoviz.org
extra:
  recipe-maintainers:
    - CurtLH
    - jbednar
    - ocefpaf
    - philippjfr
    - maximlt