travis:
  secure:
    BINSTAR_TOKEN: TV7T9b+kIaZx5wVZSuGPJzZKzcoMCRCvWyCtKOcEwpgXS+05dYmHZvel14XlEJTtVPUvrKay6ZmSxD5QMqpiOjLcD+TgPF6JONt1hhNIFcqtS/P9R1ORoEe5Em7ssuyK5mHn0eeHOO9Ci8dzF+t87JZplrWhy0ubFpOVulXevwitXgTKO635rD7+u0sORHFMGfZGUGjoL7DBAJOP5dBXtRFRYbM0tyHd/y2Qr44OTboi600a2XVaKJ/bCq5MuZ7IEyBG7k0giVeBoS5/qr/IJEmw8rBbK6mJTVUkbu4VhXsrD5QFoHNTDnzw5bgn/aYBvzPlCzE9Lwtc4XRZL2MjysyIvuOUf/BBkG/UqFA58YYQcZuONsKHuOxDMGcqjgmON0vWTtfR89G4Rra1qWyXVu/JOmncPAofbshtuk6gS/N8dZTPb/M3og6fBWLLed6gH7FIxbIs94rVUOOvZ6dZ9UvGYcOgyWD8i/B+cxnKaYkrRs72liiW+y2sKvlyODvnwmM/t7ffAFo40yMxySgFUWIsYCLioY/6O4BTU9+QcrlkrEcvPuEzB2naBaNKKOfPNruVvDOpnRMqxTw5QF7g4E8nDElyp5o8wB6gpVQ8z6Scf0JQfnRImQ2lBJK9kOyrS1V2D6wkaDqLIA0jH3eQjZIBJkEDNCU7lRRNLqLHB1E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
